name: Main Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
        
    - name: Checkout Clima
      uses: actions/checkout@v3
      with:
        path: Clima
        ref: main
        
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x
    
    - name: Build Clima
      run: dotnet build -c Release Clima/Source/Meadow.Clima.sln
